/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Simulations */
        get: operations["list_simulations_api_v1_simulations_get"];
        put?: never;
        /** Create Simulation */
        post: operations["create_simulation_api_v1_simulations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/{simulation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Simulation */
        get: operations["get_simulation_api_v1_simulations__simulation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_api_v1_applications_get"];
        put?: never;
        /** Create Application */
        post: operations["create_application_api_v1_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Application */
        get: operations["get_application_api_v1_applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/property": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Property */
        patch: operations["patch_property_api_v1_applications__application_id__property_patch"];
        trace?: never;
    };
    "/api/v1/applications/{application_id}/financials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Financials */
        patch: operations["patch_financials_api_v1_applications__application_id__financials_patch"];
        trace?: never;
    };
    "/api/v1/applications/{application_id}/personal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Personal */
        patch: operations["patch_personal_api_v1_applications__application_id__personal_patch"];
        trace?: never;
    };
    "/api/v1/applications/{application_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Application */
        post: operations["submit_application_api_v1_applications__application_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Doc Slots */
        get: operations["list_doc_slots_api_v1_applications__application_id__documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_applications__application_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Document */
        get: operations["download_document_api_v1_documents__document_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicationCreate */
        ApplicationCreate: {
            /**
             * Simulation Id
             * Format: uuid
             */
            simulation_id: string;
        };
        /** ApplicationOut */
        ApplicationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ref */
            ref: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Simulation Id */
            simulation_id: string | null;
            status: components["schemas"]["ApplicationStatus"];
            current_step: components["schemas"]["ApplicationStep"];
            /** Number Of Borrowers */
            number_of_borrowers: number;
            property_type: components["schemas"]["PropertyType"];
            property_region: components["schemas"]["Region"];
            /** Property Price */
            property_price: string;
            property_use: components["schemas"]["PropertyUse"];
            /** Main Residence */
            main_residence: boolean;
            type_of_sale: components["schemas"]["SaleType"];
            /** Epc Score */
            epc_score: number | null;
            /** Street */
            street: string | null;
            /** House Number */
            house_number: string | null;
            /** Box */
            box: string | null;
            /** City */
            city: string | null;
            /** Postal Code */
            postal_code: string | null;
            /** Own Funds */
            own_funds: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Submitted At */
            submitted_at: string | null;
            /**
             * Borrowers
             * @default []
             */
            borrowers: components["schemas"]["BorrowerOut"][];
            /**
             * Expenses
             * @default []
             */
            expenses: components["schemas"]["ExpenseOut"][];
        };
        /**
         * ApplicationStatus
         * @enum {string}
         */
        ApplicationStatus: "DRAFT" | "SUBMITTED";
        /**
         * ApplicationStep
         * @enum {string}
         */
        ApplicationStep: "PROPERTY" | "FINANCIALS" | "PERSONAL" | "DONE";
        /** ApplicationSummary */
        ApplicationSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ref */
            ref: string;
            status: components["schemas"]["ApplicationStatus"];
            current_step: components["schemas"]["ApplicationStep"];
            /** Property Price */
            property_price: string;
            /** Submitted At */
            submitted_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_upload_document_api_v1_applications__application_id__documents_post */
        Body_upload_document_api_v1_applications__application_id__documents_post: {
            doc_type: components["schemas"]["DocType"];
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Borrower Id */
            borrower_id?: string | null;
        };
        /** BorrowerFinancialsIn */
        BorrowerFinancialsIn: {
            /** Position */
            position: number;
            /** Incomes */
            incomes: components["schemas"]["IncomeIn"][];
        };
        /** BorrowerOut */
        BorrowerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Position */
            position: number;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            /** Date Of Birth */
            date_of_birth: string | null;
            /** Dependents */
            dependents: number;
            /**
             * Incomes
             * @default []
             */
            incomes: components["schemas"]["IncomeOut"][];
        };
        /** BorrowerPersonalIn */
        BorrowerPersonalIn: {
            /** Position */
            position: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /** Dependents */
            dependents: number;
        };
        /**
         * DocSlot
         * @description A required-document slot, derived per application from DocType x borrowers,
         *     joined with the Document table. status flips to UPLOADED when a Document exists.
         */
        DocSlot: {
            doc_type: components["schemas"]["DocType"];
            /** Label */
            label: string;
            /** Borrower Id */
            borrower_id?: string | null;
            /** Borrower Name */
            borrower_name?: string | null;
            /** Address Label */
            address_label?: string | null;
            status: components["schemas"]["DocSlotStatus"];
            document?: components["schemas"]["DocumentOut"] | null;
        };
        /**
         * DocSlotStatus
         * @enum {string}
         */
        DocSlotStatus: "REQUESTED" | "UPLOADED";
        /**
         * DocType
         * @enum {string}
         */
        DocType: "EPC_CERTIFICATE" | "PROOF_OF_IDENTITY" | "PAYSLIP" | "PURCHASE_AGREEMENT";
        /** DocumentOut */
        DocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Application Id
             * Format: uuid
             */
            application_id: string;
            /** Borrower Id */
            borrower_id: string | null;
            doc_type: components["schemas"]["DocType"];
            /** Filename */
            filename: string;
            /** Mime Type */
            mime_type: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** ExpenseIn */
        ExpenseIn: {
            expense_type: components["schemas"]["ExpenseType"];
            /** Monthly Amount */
            monthly_amount: number | string;
            /** Description */
            description?: string | null;
        };
        /** ExpenseOut */
        ExpenseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            expense_type: components["schemas"]["ExpenseType"];
            /** Monthly Amount */
            monthly_amount: string;
            /** Description */
            description?: string | null;
        };
        /**
         * ExpenseType
         * @enum {string}
         */
        ExpenseType: "RENT" | "EXISTING_LOAN" | "ALIMONY" | "OTHER";
        /** FinancialsStep */
        FinancialsStep: {
            /** Borrowers */
            borrowers: components["schemas"]["BorrowerFinancialsIn"][];
            /**
             * Expenses
             * @default []
             */
            expenses: components["schemas"]["ExpenseIn"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncomeIn */
        IncomeIn: {
            income_type: components["schemas"]["IncomeType"];
            /** Monthly Amount */
            monthly_amount: number | string;
        };
        /** IncomeOut */
        IncomeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            income_type: components["schemas"]["IncomeType"];
            /** Monthly Amount */
            monthly_amount: string;
        };
        /**
         * IncomeType
         * @enum {string}
         */
        IncomeType: "SALARY" | "SELF_EMPLOYED" | "CHILD_BENEFIT" | "MEAL_VOUCHERS" | "COMPANY_CAR" | "HEALTH_INSURANCE" | "RENTAL" | "OTHER";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** PersonalStep */
        PersonalStep: {
            /** Borrowers */
            borrowers: components["schemas"]["BorrowerPersonalIn"][];
        };
        /**
         * ProductType
         * @enum {string}
         */
        ProductType: "FIXED" | "VARIABLE" | "MIXED";
        /**
         * ProjectPurpose
         * @enum {string}
         */
        ProjectPurpose: "PURCHASE" | "BUILD" | "BUYOUT" | "RENOVATE" | "REFINANCE";
        /** PropertyStep */
        PropertyStep: {
            property_type: components["schemas"]["PropertyType"];
            property_region: components["schemas"]["Region"];
            /** Property Price */
            property_price: number | string;
            property_use: components["schemas"]["PropertyUse"];
            /**
             * Main Residence
             * @default true
             */
            main_residence: boolean;
            type_of_sale: components["schemas"]["SaleType"];
            /** Epc Score */
            epc_score?: number | null;
            /** Street */
            street: string;
            /** House Number */
            house_number: string;
            /** Box */
            box?: string | null;
            /** City */
            city: string;
            /** Postal Code */
            postal_code: string;
            /** Own Funds */
            own_funds: number | string;
        };
        /**
         * PropertyType
         * @enum {string}
         */
        PropertyType: "HOUSE" | "APARTMENT" | "LAND";
        /**
         * PropertyUse
         * @enum {string}
         */
        PropertyUse: "LIVING" | "RENTAL";
        /**
         * Region
         * @enum {string}
         */
        Region: "FLANDERS" | "WALLONIA" | "BRUSSELS";
        /**
         * SaleType
         * @enum {string}
         */
        SaleType: "PRIVATE" | "PUBLIC" | "NEW_BUILD";
        /** SignupRequest */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Claim Token */
            claim_token?: string | null;
        };
        /** SimulationCreate */
        SimulationCreate: {
            /** @default PURCHASE */
            project_purpose: components["schemas"]["ProjectPurpose"];
            /**
             * Number Of Borrowers
             * @default 1
             */
            number_of_borrowers: number;
            property_type: components["schemas"]["PropertyType"];
            property_region: components["schemas"]["Region"];
            /** Property Price */
            property_price: number | string;
            /** @default LIVING */
            property_use: components["schemas"]["PropertyUse"];
            /**
             * Main Residence
             * @default true
             */
            main_residence: boolean;
            /** @default PRIVATE */
            type_of_sale: components["schemas"]["SaleType"];
            /** Epc Score */
            epc_score?: number | null;
            /** Own Funds */
            own_funds: number | string;
            /** Duration Years */
            duration_years: number;
        };
        /** SimulationCreateResponse */
        SimulationCreateResponse: {
            simulation: components["schemas"]["SimulationOut"];
            /** Claim Token */
            claim_token?: string | null;
        };
        /** SimulationOut */
        SimulationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ref */
            ref: string;
            /** User Id */
            user_id: string | null;
            status: components["schemas"]["SimulationStatus"];
            project_purpose: components["schemas"]["ProjectPurpose"];
            /** Number Of Borrowers */
            number_of_borrowers: number;
            property_type: components["schemas"]["PropertyType"];
            property_region: components["schemas"]["Region"];
            /** Property Price */
            property_price: string;
            property_use: components["schemas"]["PropertyUse"];
            /** Main Residence */
            main_residence: boolean;
            type_of_sale: components["schemas"]["SaleType"];
            /** Epc Score */
            epc_score: number | null;
            /** Own Funds */
            own_funds: string;
            /** Duration Years */
            duration_years: number;
            /** Interest Rate */
            interest_rate: string;
            /** Loan Amount */
            loan_amount: string;
            /** Monthly Payment */
            monthly_payment: string;
            /** Purchase Costs */
            purchase_costs: string;
            /** Credit Costs */
            credit_costs: string;
            /** Total Project Cost */
            total_project_cost: string;
            product_type: components["schemas"]["ProductType"];
            /**
             * Apply Until
             * Format: date
             */
            apply_until: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SimulationStatus
         * @enum {string}
         */
        SimulationStatus: "ACTIVE" | "CONVERTED" | "EXPIRED";
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_simulations_api_v1_simulations_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_simulation_api_v1_simulations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_simulation_api_v1_simulations__simulation_id__get: {
        parameters: {
            query?: {
                claim_token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                simulation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_api_v1_applications_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_api_v1_applications_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_api_v1_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_property_api_v1_applications__application_id__property_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyStep"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_financials_api_v1_applications__application_id__financials_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinancialsStep"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_personal_api_v1_applications__application_id__personal_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonalStep"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_application_api_v1_applications__application_id__submit_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_doc_slots_api_v1_applications__application_id__documents_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocSlot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_applications__application_id__documents_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_applications__application_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_document_api_v1_documents__document_id__content_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
